#!/bin/sh -e

export PACKAGE="graphene_prisma"

if [ -d 'dist' ] ; then
    rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'graphene_prisma.egg-info' ] ; then
    rm -r ${PACKAGE}.egg-info
fi
