#!/bin/sh -e

export PACKAGE="graphene_prisma"

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export VERSION_SCRIPT="import sys; print('%s.%s' % sys.version_info[0:2])"
export PYTHON_VERSION=`python -c "$VERSION_SCRIPT"`

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore venv ${IGNORE_MODULES} -W ignore::DeprecationWarning --cov=${PACKAGE} --cov=tests --cov-fail-under=0 --cov-report=term-missing ${@}
${PREFIX}autoflake --recursive ${PACKAGE} tests
if [ "${PYTHON_VERSION}" = '3.7' ]; then
    echo "Skipping 'black' on 3.7. See issue https://github.com/ambv/black/issues/494"
else
    ${PREFIX}black ${PACKAGE} tests --check
fi
